apiVersion: v1
kind: Pod
metadata:
  name: Multi-Container
  labels:
  purpose: Multi-Container
spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almaliux:9
    command: ["sleep", "1000"]