apiVersion: v1
kind: Pod
metadata:
  name: multi-Container
  labels:
    purpose: multi-Container
spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almaliux:9
    command: ["sleep", "1000"]