apiVersion: v1
kind: labels
metadata:
  name: frontend
  labels: 
    project: roboshop
    component: frontend
    environment: dev
    version: v1
  spec:
    containers:
    - name: frontend
      image: nginx