apiVersion: v1                      # Core Kubernetes API version
kind: Service                       # Resource type: Service (exposes Pods over network)

metadata:
  name: nginx-np                    # Name of the Service (used as DNS inside cluster)

spec:
  type: NodePort                    # Exposes Service on each Node's IP at a static port (NodePort)

  selector:                         # Used to match target Pods via labels
    project: roboshop               # Must match Pod label
    component: frontend             # Must match Pod label
    environment: dev                # Must match Pod label
    purpose: node-port              # EXTRA label → Pod MUST also have this (or no endpoints)

  ports:                            # Port mapping configuration
  - protocol: TCP                   # Protocol used (default TCP)
    port: 80                        # Service port (cluster-internal access)
    targetPort: 80                  # Container port inside Pod
    # nodePort: 30007               # (Optional) Fixed external port (range: 30000–32767)