apiVersion: v1                      # Core Kubernetes API version
kind: Pod                           # Resource type: Pod

metadata:
  name: service-lb-demo             # Name of the Pod

  labels:                           # Labels used for Service selection
    project: roboshop               # Must match Service selector
    component: frontend             # Must match Service selector
    environment: dev                # Must match Service selector
    purpose: load-balancer          # ⚠️ This MUST match Service selector exactly

spec:
  containers:
  - name: nginx                     # Container name
    image: nginx                    # nginx web server image