apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  labels:
    app: snginx-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app

  template:
    metadata:
      labels:
        app: nginx-app

    spec:
      containers:
      - name: nginx-app
        image: nginx
        volumeMounts:
        - name: db-connection
          mountPath: /opt
        ports:
        - containerPort: 8000
        volumes:
        - name: db-connection
          ConfigMap:
            name: test-configmap